const ACTION_LOAD_DATA = 'ACTION_LOAD_DATA'
const ACTION_UPDATE_REVIEWS = 'ACTION_UPDATE_REVIEWS'
const ACTION_ADD_PRODUCT = 'ACTION_ADD_PRODUCT'
const ACTION_ADD_FAVORITE = 'ACTION_ADD_FAVORITE'



export {ACTION_LOAD_DATA, ACTION_UPDATE_REVIEWS, ACTION_ADD_PRODUCT, ACTION_ADD_FAVORITE}